[versions]
activity = "1.13.0"
agp = "9.2.1"
okhttp = "5.4.0"
coroutines = "1.11.0"
streamWebrtc = "1.3.10"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
stream-webrtc-android = { group = "io.getstream", name = "stream-webrtc-android", version.ref = "streamWebrtc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
