from __future__ import annotations

DEFAULT_OVERSHOOT_API_URL = "https://api.overshoot.ai/v1beta"
DEFAULT_OVERSHOOT_MODEL = "Qwen/Qwen3.6-35B-A3B-FP8"

PHASE_WAITING = "WAITING_FOR_START"
PHASE_GUIDING = "GUIDING"
PHASE_STEP_DONE = "STEP_DONE"
PHASE_COMPLETED = "COMPLETED"
PHASE_ERROR = "ERROR"

ANDROID_CHANNEL_LABEL = "session-events"
DEMO_CHANNEL_LABEL = "demo-events"
VIDEO_CLOCK_RATE = 90_000
DEMO_FPS = 5
OVERSHOOT_FPS = 5
OVERSHOOT_PUBLISH_MAX_BITRATE_BPS = 5_000_000
OVERSHOOT_PROMPT_INTERVAL_SECONDS = 0.5
OVERSHOOT_KEEPALIVE_INTERVAL_SECONDS = 90.0
OVERSHOOT_STREAM_READY_TIMEOUT_SECONDS = 15.0
OVERSHOOT_RECONNECT_INGEST_TIMEOUT_SECONDS = 15.0
OVERSHOOT_STREAM_STATUS_POLL_SECONDS = 0.5
OVERSHOOT_CHAT_COMPLETION_TIMEOUT_SECONDS = 30.0
AIORTC_H264_DEFAULT_BITRATE = 2_000_000
AIORTC_H264_MIN_BITRATE = 500_000
AIORTC_H264_MAX_BITRATE = 3_000_000
DEBUG_COMPOSITE_INTERVAL_SECONDS = 1.0
OVERSHOOT_STEP_RESULT_GRACE_SECONDS = 0.6
DEMO_BACKGROUND_BRIGHTNESS = 0.68
HUD_WIDTH = 480
HUD_HEIGHT = 640
HUD_GREEN = (0, 255, 96)
HUD_DIM_GREEN = (28, 190, 82)
HUD_DENSITY = 1.5
