name: JS CI

on:
  pull_request:
    paths:
      - "js/**"
      - ".github/workflows/js-ci.yml"
      - ".github/workflows/release.yml"
  push:
    branches:
      - main
    paths:
      - "js/**"
      - ".github/workflows/js-ci.yml"
      - ".github/workflows/release.yml"

jobs:
  test-js:
    name: Test JS create package
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        working-directory: js

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: js/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Check package contents
        run: npm pack --dry-run
